#!/bin/sh

# TODO: Make button handles for brightness
#case $BLOCK_BUTTON in
         #1) setsid "$TERMINAL" -e alsamixer & ;;
	## 2) amixer sset Master toggle ;;
	## 4) amixer sset Master 5%+ >/dev/null 2>/dev/null ;;
	## 5) amixer sset Master 5%- >/dev/null 2>/dev/null ;;
	##1) setsid "$TERMINAL" -e pulsemixer & ;;
	#2) pamixer -t ;;
	#4) pamixer --allow-boost -i 1 ;;
	#5) pamixer --allow-boost -d 1 ;;
	#3) notify-send "Volume module" "\- Shows volume.
#- Middle click to mute.
#- Scroll to change." ;;
	#6) "$TERMINAL" -e "$EDITOR" "$0" ;;
#esac

backlight="$(xbacklight)"

percent="$(echo "$backlight" | grep -Poi '^[^\.]*' | sed "s,.* \([0-9]\+\).*,\1,;1q")"

if [ "$percent" -gt "70" ]; then
	icon=" "
elif [ "$percent" -lt "30" ]; then
	icon=" "
else
	icon=" "
fi

printf "%s%s%%\\n" "$icon" "$percent"
