#!/bin/sh

# Prints the current volume or if muted. Uses PulseAudio by default,
# uncomment the ALSA lines if you remove PulseAudio.

case $BLOCK_BUTTON in
         1) setsid "$TERMINAL" -e alsamixer & ;;
	# 2) amixer sset Master toggle ;;
	# 4) amixer sset Master 5%+ >/dev/null 2>/dev/null ;;
	# 5) amixer sset Master 5%- >/dev/null 2>/dev/null ;;
	#1) setsid "$TERMINAL" -e pulsemixer & ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	3) notify-send "Volume module" "\- Shows volume.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

mute_state="$(pamixer --get-mute)"
vol_state="$(pamixer --get-volume)"
# volstat="$(amixer get Master)" # ALSA only equivalent.

echo "$mute_state" | grep -q "true" && printf "婢 \\n" && exit
# echo "$volstat" | grep "\[off\]" >/dev/null && printf "婢\\n" && exit # ALSA

vol="$(echo "$vol_state" | grep '[0-9]\+' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"
# vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed "s/[^0-9]*//g;1q") # ALSA

if [ "$vol" -gt "70" ]; then
	icon="墳 "
elif [ "$vol" -lt "30" ]; then
	icon="奄 "
else
	icon="奔 "
fi

printf "%s%s%%\\n" "$icon" "$vol"
